changelog:
  exclude:
    labels:
      - skip-changelog
  categories:
    - title: New features
      labels:
        - enhancement
    - title: Bug fixes
      labels:
        - bug
    - title: Documentation and maintenance
      labels:
        - documentation
        - chore
    - title: Other changes
      labels:
        - '*'
